# Generated by Django 4.2.7 on 2023-11-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_workitem_meta_description_workitem_meta_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitem',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='our_works_category',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='our_works_category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
