# Generated by Django 4.2.7 on 2023-11-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_product_category_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_style_category',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='our_style_category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
