# Generated by Django 4.2.7 on 2023-11-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_our_style_category_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product_category',
            name='alt_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
