# Generated by Django 4.2.7 on 2023-12-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_product_alt_text_product_category_alt_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='product_category',
            name='alt_text',
        ),
    ]
