# Generated by Django 5.0 on 2023-12-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
